[build]
  publish = "public"
  functions = "netlify/functions"
  command = "npm install && npm install --prefix netlify/functions"

[build.environment]
  NODE_VERSION = "18"

[dev]
  port = 8888
  functionsPort = 9999
  publish = "public"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
